// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeSAVINGS  AccountType = "SAVINGS"
	AccountTypeCHECKING AccountType = "CHECKING"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType
	Valid       bool // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type TransactionStatus string

const (
	TransactionStatusFAILED  TransactionStatus = "FAILED"
	TransactionStatusPENDING TransactionStatus = "PENDING"
	TransactionStatusSUCCESS TransactionStatus = "SUCCESS"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus
	Valid             bool // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type TransactionType string

const (
	TransactionTypeDEPOSIT     TransactionType = "DEPOSIT"
	TransactionTypeWITHDRAW    TransactionType = "WITHDRAW"
	TransactionTypeTRANSFER    TransactionType = "TRANSFER"
	TransactionTypeBILLPAYMENT TransactionType = "BILL_PAYMENT"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType
	Valid           bool // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Account struct {
	Balance       int64
	Type          AccountType
	FkUserID      uuid.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	AccountNumber uuid.UUID
}

type CheckingAccount struct {
	AccountID      uuid.UUID
	OverdraftLimit pgtype.Numeric
	MaintenanceFee int64
}

type SavingsAccount struct {
	AccountID       uuid.UUID
	InterestRate    pgtype.Numeric
	MinBalance      int64
	WithdrawalLimit int64
}

type Session struct {
	ID       uuid.UUID
	FkUserID uuid.UUID
}

type Transaction struct {
	ID          uuid.UUID
	Type        TransactionType
	Status      TransactionStatus
	Amount      int64
	FkSender    uuid.UUID
	FkRecipient pgtype.UUID
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID          uuid.UUID
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber string
	Address     string
	Password    string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
