// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const depositTransaction = `-- name: DepositTransaction :one
INSERT INTO transactions (type, status, amount, fk_sender)
VALUES (
    'DEPOSIT',
    $1,
    $2,
    $3
)
RETURNING id, type, status, amount, fk_sender, fk_recipient, created_at
`

type DepositTransactionParams struct {
	Status   TransactionStatus
	Amount   int64
	FkSender uuid.UUID
}

func (q *Queries) DepositTransaction(ctx context.Context, arg DepositTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, depositTransaction, arg.Status, arg.Amount, arg.FkSender)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.FkSender,
		&i.FkRecipient,
		&i.CreatedAt,
	)
	return i, err
}

const transferTransaction = `-- name: TransferTransaction :one
INSERT INTO transactions (type, status, amount, fk_sender, fk_recipient)
VALUES (
    'TRANSFER',
    $1,
    $2,
    $3,
    $4
)
RETURNING id, type, status, amount, fk_sender, fk_recipient, created_at
`

type TransferTransactionParams struct {
	Status      TransactionStatus
	Amount      int64
	FkSender    uuid.UUID
	FkRecipient pgtype.UUID
}

func (q *Queries) TransferTransaction(ctx context.Context, arg TransferTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, transferTransaction,
		arg.Status,
		arg.Amount,
		arg.FkSender,
		arg.FkRecipient,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.FkSender,
		&i.FkRecipient,
		&i.CreatedAt,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :execrows
UPDATE transactions
SET
    status = $2
WHERE id = $1
`

type UpdateTransactionStatusParams struct {
	ID     uuid.UUID
	Status TransactionStatus
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransactionStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const withdrawTransaction = `-- name: WithdrawTransaction :one
INSERT INTO transactions (type, status, amount, fk_sender)
VALUES (
    'WITHDRAW',
    $1,
    $2,
    $3
)
RETURNING id, type, status, amount, fk_sender, fk_recipient, created_at
`

type WithdrawTransactionParams struct {
	Status   TransactionStatus
	Amount   int64
	FkSender uuid.UUID
}

func (q *Queries) WithdrawTransaction(ctx context.Context, arg WithdrawTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, withdrawTransaction, arg.Status, arg.Amount, arg.FkSender)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Amount,
		&i.FkSender,
		&i.FkRecipient,
		&i.CreatedAt,
	)
	return i, err
}
