// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (fk_user_id)
VALUES (
    fk_user_id = $1
)
RETURNING id
`

func (q *Queries) CreateSession(ctx context.Context, fkUserID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSession, fkUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findUserByPhone = `-- name: FindUserByPhone :one
SELECT id, first_name, last_name, email, phone_number, address, password, created_at, updated_at FROM users
WHERE phone_number = $1
`

func (q *Queries) FindUserByPhone(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByPhoneOrEmail = `-- name: FindUserByPhoneOrEmail :one
SELECT id, first_name, last_name, email, phone_number, address, password, created_at, updated_at FROM users
WHERE phone_number = $1 OR email = $2
`

type FindUserByPhoneOrEmailParams struct {
	PhoneNumber string
	Email       string
}

func (q *Queries) FindUserByPhoneOrEmail(ctx context.Context, arg FindUserByPhoneOrEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, findUserByPhoneOrEmail, arg.PhoneNumber, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerUser = `-- name: RegisterUser :one
INSERT INTO users (first_name, last_name, email, phone_number, address, password)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, first_name, last_name, email, phone_number, address, password, created_at, updated_at
`

type RegisterUserParams struct {
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber string
	Address     string
	Password    string
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRow(ctx, registerUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.Address,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.Address,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
